### ISSUE TITLE
ECONNRESET error when a tcp client disconnects

### ISSUE THREAD

**Issue by kcbob2000** [hitgeek/simple-hl7#36]
I have the sample code working great as a server; I can send and receive ACK's wonderfully, but whenever I disconnect the client that is sending the hl7, I get an unhandled error message:

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I have tried setting breakpoints in the app.use(.... err) function, but that never gets hit so I'm not sure how I can handle that situation and keep the server running?

**Comment by hitgeek** [comment]
maybe try
```
app.server.on('error', function(err) {
  //handle the error. 
})
```

**Comment by kcbob2000** [comment]
There is no ‘app.server’ object.  I tried 

 

app.on('error', function (err) {

    console.log('Caught it!');

})

 

And it never reaches here, it still throws the same error and I can’t trap it to get a stack trace or anything…

**Comment by hitgeek** [comment]
you will only have app.server after calling `start`.

```
var app = hl7.tcp();
//app.server is undefined
app.start(8080);
//now you have a server
app.server.on('error', function(err) {
})
```

or it looks like `start` returns the server so you could do 
```
var app = hl7.tcp();
//app.server is undefined
var server = app.start(8080);
//now you have a server
server.on('error', function(err) {
})
```

**Comment by kcbob2000** [comment]
I do see it after start(), thanks.  It still doesn’t catch the error though and putting the start() results in a variable won’t catch it either.  

 

//Listen on port 7777

var server = app.start(7777);

 

server.on('error', function (err) {

    console.log('Caught it!');

})

**Comment by hitgeek** [comment]
maybe the error is coming from this socket. https://github.com/hitgeek/simple-hl7/blob/master/lib/server/tcp-server.js#L56

crack open your node_modules folder and find that file. tcp-server.js

try adding a handler for `socket.on('error', handler)`

if that works I'll add in a way to pass that handler in, or access that underlying socket or something.

**Comment by kcbob2000** [comment]
That caught it!

**Comment by hitgeek** [comment]
I pushed a new verison 3.2.

those errors should now get handled by the error middleware from app.use(...errr)

https://github.com/hitgeek/simple-hl7/blob/master/lib/server/tcp-server.js#L76

can you confirm if that is the case?

thanks

**Comment by kcbob2000** [comment]
If I take the error handler out of tcp-server.js, it still throws and stops the execution.  I upgraded to 3.2.1, is that the right one?

 

I tried 

 

app.server.on('error', function (err) {

    console.log('Caught it in app.js!');

});

 

 

And also 

 

let server = app.start(7777);

 

server.on('error', function (err) {

    console.log('Caught it in app.js!');

});

**Comment by hitgeek** [comment]
yea, 3.2.1 should work. 

the error should end up in your here error handler for the app. 

```
app.use(function(err, req, res, next) {
  if (err == 'ECONNRESET') {
    return next();
  }

  //error handler
  //standard error middleware would be
  console.log('******ERROR*****')
  console.log(err);
  var msa = res.ack.getSegment('MSA');
  msa.setField(1, 'AR');
  res.ack.addSegment('ERR', err.message);
  res.end();
});
```

**Comment by kcbob2000** [comment]
Never makes it to app.use, never even gets to the “if (err “ statement.

**Comment by kcbob2000** [comment]
I got it to fail without disconnecting the socket but just putting a ‘throw’ in tcp-server.js (TcpServer.prototype.start function):

 

this.server = net.createServer(function (socket) {

throw;
